## 기초4_문제

In [1]:
import pandas as pd
import numpy as np

In [2]:
'''
seaborn의 타이타닉 데이터를 불러오자
'''

import seaborn as sns
df = sns.load_dataset('titanic')


In [3]:
'''
실습을 위에 데이터 소실 만들기
변경 없이 실행 시켜주시면 됩니다.
'''
df.loc[1, 'pclass'] = '?'

In [3]:
'''
데이터구조 확인 (기계적으로 확인하자)
'''


'\n데이터구조 확인 (기계적으로 확인하자)\n'

In [4]:
'''
pclass 열의 자료형 확인 _문자열(object)
df['열'].unique() 활용
'''


array([3, '?', 1, 2], dtype=object)

In [5]:
'''
pclass의 목록 확인
'''


3    491
1    215
2    184
?      1
Name: pclass, dtype: int64

In [7]:
'''
pclass열의 누락 데이터('?') 삭제 후에 문자열을 정수형으로 변경
'''

In [8]:
'''
pclass 열의 자료형 확인 _int
'''


int32


In [9]:
'''
df['열'].unique() 를 활용하여
pclass 열의 고유값 확인
'''


array([3, 1, 2])

In [10]:
'''
정수형 데이터를 문자형 데이터로 변환 
1을 1등급으로 변경
2를 2등급으로 변경
3을 3등급으로 변경
'''


array(['3등급', '1등급', '2등급'], dtype=object)

In [11]:
'''
pclass 열의 자료형 확인 _object
'''
 

object


In [12]:
'''
origin 열의 문자열 자료형을 범주형으로 변환
'''


category


In [13]:
'''
origin 열의 범주형을 문자열로 다시 변환
'''


object


In [14]:
'''
fare열을 np.histogram 함수로 3개의 bin으로 나누는 경계 값의 리스트 구하기

'''

[870  17   3]

[  0.     170.7764 341.5528 512.3292]


In [15]:
'''
위에서 구한 세가지의 그룹을 ['하', '중', '상']로 변경해 보자
'''


In [16]:
'''위의 변경값 확인'''


        fare fare_bin
881   7.8958        하
882  10.5167        하
883  10.5000        하
884   7.0500        하
885  29.1250        하
886  13.0000        하
887  30.0000        하
888  23.4500        하
889  30.0000        하
890   7.7500        하


In [17]:
'''
fare_bin 열의 범주형 데이터를 더미 변수로 변환
'''


    하  중  상
0   1  0  0
2   1  0  0
3   1  0  0
4   1  0  0
5   1  0  0
6   1  0  0
7   1  0  0
8   1  0  0
9   1  0  0
10  1  0  0
11  1  0  0
12  1  0  0
13  1  0  0
14  1  0  0
15  1  0  0
